### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by caneta** [fgrsnau/ncm2-otherbuf#6]
The installation instructions inside README.md file refers to a previous version of the plugin.
They are
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'roxma/nvim-completion-manager'
Plug 'fgrsnau/ncm-otherbuf'
call plug#end()
```
but should be
```
call plug#begin('~/.config/nvim/plugins')
Plug 'ncm2/ncm2'
Plug 'fgrsnau/ncm2-otherbuf', { 'branch': 'ncm2' }
call plug#end()
```

**Comment by fgrsnau** [comment]
I honestly would rather like to make the `ncm2` brach default and/or rename it to master. This would break all the existing setups though.

**Comment by caneta** [comment]
Renaming the `ncm2` branch into `master` should be the best.
I understand that this is a breaking change but updating the README with a Warning describing this change, should be enough IMHO.

**Comment by lougxing** [comment]
This is my config, have no effect .

````
$ git status
# On branch ncm2
nothing to commit, working directory clean
````

````
call plug#begin()
"completion
Plug 'ncm2/ncm2'
Plug 'fgrsnau/ncm2-otherbuf', { 'branch': 'ncm2' }
call plug#end()

"Plug 'roxma/nvim-yarp'
"Plug 'ncm2/ncm2-bufword'
"Plug 'ncm2/ncm2-path'
"Plug 'fgrsnau/ncm2-otherbuf'
"Plug 'fgrsnau/ncm2-aspell'
"Plug 'filipekiss/ncm2-look.vim'

let g:python3_host_prog="/usr/bin/python3"

syntax enable
set background=dark

"completion
"autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect

let g:ncm2_look_enabled = 1
let g:ncm2_look_mark = 'l'

set spellfile=~/.vim/spell/en.utf-8.add

`````

**Comment by FatBoyXPC** [comment]
Instead of renaming `ncm2` to `master`, how about creating master from `ncm2` and never update the `ncm2` branch? You could include a bit in the README about this if people are wondering why they aren't getting updates.

I came here to see if this was mentioned because I'm annoyed of `:PlugUpdate` giving me this error and figured other people might not know how to specify the branch with vim-plug.

```
x ncm2-otherbuf:
    fatal: invalid reference: master
```

**Comment by fgrsnau** [comment]
The correct branch is now `master`. Using the branch `ncm2` should display a message during startup.
